# Week 3 - NumPy and Pandas

## Objective
Learn how to use NumPy and Pandas for data manipulation, cleaning, and basic analysis.

## Topics Covered
- NumPy arrays
- NumPy operations
- Broadcasting
- Pandas Series
- Pandas DataFrames
- Indexing
- Grouping
- Data cleaning
- Data aggregation

In [1]:
#import pandas and numpy
import numpy as np
import pandas as pd

In [2]:
np.array([10,20,30])

array([10, 20, 30])

In [3]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

## creating numpy array

In [6]:
numbers = np.array([10,20,30,40,50,60])

print(numbers)
print(type(numbers))

[10 20 30 40 50 60]
<class 'numpy.ndarray'>

## numpy array operations

In [7]:
numbers = np.array([10, 20, 30, 40, 50])

print("Addition:", numbers + 5)
print("Subtraction:", numbers - 5)
print("Multiplication:", numbers * 2)
print("Division:", numbers / 10)

Addition: [15 25 35 45 55]
Subtraction: [ 5 15 25 35 45]
Multiplication: [ 20  40  60  80 100]
Division: [1. 2. 3. 4. 5.]

## numpy aggregtion operations

In [8]:
numbers = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(numbers))
print("Mean:", np.mean(numbers))
print("Maximum:", np.max(numbers))
print("Minimum:", np.min(numbers))

Sum: 150
Mean: 30.0
Maximum: 50
Minimum: 10

## numpy broadcasting

In [9]:
numbers = np.array([10, 20, 30, 40, 50])

result = numbers + 10

print("Original array:", numbers)
print("After adding 10:", result)

Original array: [10 20 30 40 50]
After adding 10: [20 30 40 50 60]

## 2D numpy array

In [10]:
marks = np.array([
    [80, 75, 90],
    [65, 88, 70],
    [92, 85, 95]
])

print(marks)
print("Shape:", marks.shape)

[[80 75 90]
 [65 88 70]
 [92 85 95]]
Shape: (3, 3)

## Access Elements in a 2D NumPy Array

In [11]:
marks = np.array([
    [80, 75, 90],
    [65, 88, 70],
    [92, 85, 95]
])

print("First row:", marks[0])
print("First value:", marks[0, 0])
print("Second row, third value:", marks[1, 2])

First row: [80 75 90]
First value: 80
Second row, third value: 70

## NumPy Array Calculations

In [12]:
marks = np.array([
    [80, 75, 90],
    [65, 88, 70],
    [92, 85, 95]
])

print("Total of all marks:", np.sum(marks))
print("Average of all marks:", np.mean(marks))

print("Total for each student:", np.sum(marks, axis=1))
print("Average for each student:", np.mean(marks, axis=1))

Total of all marks: 740
Average of all marks: 82.22222222222223
Total for each student: [245 223 272]
Average for each student: [81.66666667 74.33333333 90.66666667]

## numpy filtering

In [13]:
marks = np.array([45, 67, 82, 39, 91, 56, 73])

passed_marks = marks[marks >= 50]

print("All marks:", marks)
print("Passed marks:", passed_marks)

All marks: [45 67 82 39 91 56 73]
Passed marks: [67 82 91 56 73]

## Pandas Series

In [14]:
import pandas as pd

marks = pd.Series([80, 75, 90, 65, 88])

print(marks)
print("Average:", marks.mean())
print("Maximum:", marks.max())
print("Minimum:", marks.min())

0    80
1    75
2    90
3    65
4    88
dtype: int64
Average: 79.6
Maximum: 90
Minimum: 65

## Pandas Series with Custom Index

In [15]:
marks = pd.Series(
    [80, 75, 90, 65, 88],
    index=["Math", "Python", "SQL", "ML", "Statistics"]
)

print(marks)

Math          80
Python        75
SQL           90
ML            65
Statistics    88
dtype: int64

In [16]:
#access a particular value
print("Python marks:", marks["Python"])
print("ML marks:", marks["ML"])

Python marks: 75
ML marks: 65

## Creating a Pandas DataFrame

In [17]:
data = {
    "Name": ["Ranjita", "Anu", "Priya", "Rahul"],
    "Age": [20, 21, 20, 22],
    "Marks": [85, 78, 92, 74]
}

df = pd.DataFrame(data)

print(df)

      Name  Age  Marks
0  Ranjita   20     85
1      Anu   21     78
2    Priya   20     92
3    Rahul   22     74

## Accessing DataFrame Columns

In [20]:
data = {
    "Name": ["Ranjita", "Anu", "Priya", "Rahul"],
    "Age": [20, 21, 20, 22],
    "Marks": [85, 78, 92, 74]
}

df = pd.DataFrame(data)

print("Names:")
print(df[["Name", "Marks"]])

Names:
      Name  Marks
0  Ranjita     85
1      Anu     78
2    Priya     92
3    Rahul     74

## Pandas Indexing with loc and iloc

In [21]:
data = {
    "Name": ["Ranjita", "Anu", "Priya", "Rahul"],
    "Age": [20, 21, 20, 22],
    "Marks": [85, 78, 92, 74]
}

df = pd.DataFrame(data)

print("First row:")
print(df.iloc[0])

print("\nFirst two rows:")
print(df.iloc[0:2])

First row:
Name     Ranjita
Age           20
Marks         85
Name: 0, dtype: object

First two rows:
      Name  Age  Marks
0  Ranjita   20     85
1      Anu   21     78

## Pandas loc

In [22]:
data = {
    "Name": ["Ranjita", "Anu", "Priya", "Rahul"],
    "Age": [20, 21, 20, 22],
    "Marks": [85, 78, 92, 74]
}

df = pd.DataFrame(data)

print("First row:")
print(df.loc[0])

print("\nName and Marks:")
print(df.loc[:, ["Name", "Marks"]])

First row:
Name     Ranjita
Age           20
Marks         85
Name: 0, dtype: object

Name and Marks:
      Name  Marks
0  Ranjita     85
1      Anu     78
2    Priya     92
3    Rahul     74

## Filtering Data in Pandas

In [23]:
data = {
    "Name": ["Ranjita", "Anu", "Priya", "Rahul"],
    "Age": [20, 21, 20, 22],
    "Marks": [85, 78, 92, 74]
}

df = pd.DataFrame(data)

high_marks = df[df["Marks"] >= 80]

print(high_marks)

      Name  Age  Marks
0  Ranjita   20     85
2    Priya   20     92

## Add a New Column to a DataFrame

In [24]:
data = {
    "Name": ["Ranjita", "Anu", "Priya", "Rahul"],
    "Age": [20, 21, 20, 22],
    "Marks": [85, 78, 92, 74]
}

df = pd.DataFrame(data)

df["Passed"] = df["Marks"] >= 50

print(df)

      Name  Age  Marks  Passed
0  Ranjita   20     85    True
1      Anu   21     78    True
2    Priya   20     92    True
3    Rahul   22     74    True

## Modify DataFrame Values

In [25]:
data = {
    "Name": ["Ranjita", "Anu", "Priya", "Rahul"],
    "Age": [20, 21, 20, 22],
    "Marks": [85, 78, 92, 74]
}

df = pd.DataFrame(data)

df.loc[1, "Marks"] = 82

print(df)

      Name  Age  Marks
0  Ranjita   20     85
1      Anu   21     82
2    Priya   20     92
3    Rahul   22     74

## Check Basic DataFrame Information

In [26]:
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns)

print("\nData types:")
print(df.dtypes)

print("\nFirst 5 rows:")
print(df.head())

Shape: (4, 3)

Columns:
Index(['Name', 'Age', 'Marks'], dtype='object')

Data types:
Name     object
Age       int64
Marks     int64
dtype: object

First 5 rows:
      Name  Age  Marks
0  Ranjita   20     85
1      Anu   21     82
2    Priya   20     92
3    Rahul   22     74

## Descriptive Statistics with Pandas

In [27]:
print("Average marks:", df["Marks"].mean())
print("Highest marks:", df["Marks"].max())
print("Lowest marks:", df["Marks"].min())
print("Total marks:", df["Marks"].sum())

Average marks: 83.25
Highest marks: 92
Lowest marks: 74
Total marks: 333

## Grouping Data with groupby()

In [28]:
data = {
    "Name": ["Ranjita", "Anu", "Priya", "Rahul", "Sneha"],
    "Branch": ["AIML", "CSE", "AIML", "CSE", "AIML"],
    "Marks": [85, 78, 92, 74, 88]
}

df = pd.DataFrame(data)

branch_average = df.groupby("Branch")["Marks"].mean()

print(branch_average)

Branch
AIML    88.333333
CSE     76.000000
Name: Marks, dtype: float64

## Grouping with Multiple Aggregations

In [29]:
data = {
    "Name": ["Ranjita", "Anu", "Priya", "Rahul", "Sneha"],
    "Branch": ["AIML", "CSE", "AIML", "CSE", "AIML"],
    "Marks": [85, 78, 92, 74, 88]
}

df = pd.DataFrame(data)

branch_stats = df.groupby("Branch")["Marks"].agg(
    ["mean", "max", "min", "count"]
)

print(branch_stats)

             mean  max  min  count
Branch
AIML    88.333333   92   85      3
CSE     76.000000   78   74      2

## Handling Missing Values

In [30]:
data = {
    "Name": ["Ranjita", "Anu", "Priya", "Rahul", "Sneha"],
    "Marks": [85, 78, None, 74, 88],
    "Age": [20, 21, 20, None, 22]
}

df = pd.DataFrame(data)

print("Original data:")
print(df)

print("\nMissing values:")
print(df.isnull().sum())

Original data:
      Name  Marks   Age
0  Ranjita   85.0  20.0
1      Anu   78.0  21.0
2    Priya    NaN  20.0
3    Rahul   74.0   NaN
4    Sneha   88.0  22.0

Missing values:
Name     0
Marks    1
Age      1
dtype: int64

## Remove Missing Values

In [31]:
cleaned_df = df.dropna()

print("Original number of rows:", len(df))
print("Rows after removing missing values:", len(cleaned_df))

print("\nCleaned data:")
print(cleaned_df)

Original number of rows: 5
Rows after removing missing values: 3

Cleaned data:
      Name  Marks   Age
0  Ranjita   85.0  20.0
1      Anu   78.0  21.0
4    Sneha   88.0  22.0

## Fill Missing Values

In [32]:
data = {
    "Name": ["Ranjita", "Anu", "Priya", "Rahul", "Sneha"],
    "Marks": [85, 78, None, 74, 88],
    "Age": [20, 21, 20, None, 22]
}

df = pd.DataFrame(data)

df["Marks"] = df["Marks"].fillna(df["Marks"].mean())
df["Age"] = df["Age"].fillna(df["Age"].mean())

print(df)

      Name  Marks    Age
0  Ranjita  85.00  20.00
1      Anu  78.00  21.00
2    Priya  81.25  20.00
3    Rahul  74.00  20.75
4    Sneha  88.00  22.00

## Sorting Data with Pandas

In [34]:
data = {
    "Name": ["Ranjita", "Anu", "Priya", "Rahul", "Sneha"],
    "Marks": [85, 78, 92, 74, 88]
}

df = pd.DataFrame(data)

sorted_df = df.sort_values("Marks", ascending=True)

print(sorted_df)

      Name  Marks
3    Rahul     74
1      Anu     78
0  Ranjita     85
4    Sneha     88
2    Priya     92

## Save a DataFrame as a CSV File

In [35]:
data = {
    "Name": ["Ranjita", "Anu", "Priya", "Rahul"],
    "Marks": [85, 78, 92, 74]
}

df = pd.DataFrame(data)

df.to_csv("student_marks.csv", index=False)

print("Dataset saved successfully!")

Dataset saved successfully!

## Load a CSV File with Pandas

In [37]:
df = pd.read_csv("student_marks.csv")
df

      Name  Marks
0  Ranjita     85
1      Anu     78
2    Priya     92
3    Rahul     74

## Load a Dataset and Inspect It

In [38]:
df = pd.read_csv("student_marks.csv")

print("First 5 rows:")
print(df.head())

print("\nDataset shape:")
print(df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nBasic information:")
df.info()

First 5 rows:
      Name  Marks
0  Ranjita     85
1      Anu     78
2    Priya     92
3    Rahul     74

Dataset shape:
(4, 2)

Column names:
['Name', 'Marks']

Basic information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Marks   4 non-null      int64
dtypes: int64(1), object(1)
memory usage: 196.0+ bytes

## Get Summary Statistics with describe()

In [39]:
df.describe()

           Marks
count   4.000000
mean   82.250000
std     7.932003
min    74.000000
25%    77.000000
50%    81.500000
75%    86.750000
max    92.000000

## Practice value_counts()

In [40]:
data = {
    "Name": ["Ranjita", "Anu", "Priya", "Rahul", "Sneha", "Amit"],
    "Branch": ["AIML", "CSE", "AIML", "CSE", "AIML", "CSE"],
    "Marks": [85, 78, 92, 74, 88, 81]
}

df = pd.DataFrame(data)

print(df["Branch"].value_counts())

Branch
AIML    3
CSE     3
Name: count, dtype: int64

## Filtering with Multiple Conditions

In [41]:
data = {
    "Name": ["Ranjita", "Anu", "Priya", "Rahul", "Sneha", "Amit"],
    "Branch": ["AIML", "CSE", "AIML", "CSE", "AIML", "CSE"],
    "Marks": [85, 78, 92, 74, 88, 81]
}

df = pd.DataFrame(data)

result = df[(df["Branch"] == "AIML") & (df["Marks"] >= 85)]

print(result)

      Name Branch  Marks
0  Ranjita   AIML     85
2    Priya   AIML     92
4    Sneha   AIML     88

## Combining NumPy and Pandas

In [42]:
data = {
    "Name": ["Ranjita", "Anu", "Priya", "Rahul"],
    "Marks": [85, 78, 92, 74]
}

df = pd.DataFrame(data)

df["Marks_Doubled"] = np.array(df["Marks"]) * 2

print(df)

      Name  Marks  Marks_Doubled
0  Ranjita     85            170
1      Anu     78            156
2    Priya     92            184
3    Rahul     74            148

## Rename Columns

In [43]:
data = {
    "student_name": ["Ranjita", "Anu", "Priya", "Rahul"],
    "student_marks": [85, 78, 92, 74]
}

df = pd.DataFrame(data)

df = df.rename(columns={
    "student_name": "Name",
    "student_marks": "Marks"
})

print(df)

      Name  Marks
0  Ranjita     85
1      Anu     78
2    Priya     92
3    Rahul     74

## Remove Duplicate Rows

In [44]:
data = {
    "Name": ["Ranjita", "Anu", "Priya", "Anu", "Rahul"],
    "Marks": [85, 78, 92, 78, 74]
}

df = pd.DataFrame(data)

print("Original data:")
print(df)

print("\nNumber of duplicate rows:", df.duplicated().sum())

df_cleaned = df.drop_duplicates()

print("\nAfter removing duplicates:")
print(df_cleaned)

Original data:
      Name  Marks
0  Ranjita     85
1      Anu     78
2    Priya     92
3      Anu     78
4    Rahul     74

Number of duplicate rows: 1

After removing duplicates:
      Name  Marks
0  Ranjita     85
1      Anu     78
2    Priya     92
4    Rahul     74

## Check for Missing Values After Cleaning

In [45]:
data = {
    "Name": ["Ranjita", "Anu", "Priya", "Rahul"],
    "Marks": [85, 78, 92, 74],
    "Age": [20, 21, None, 22]
}

df = pd.DataFrame(data)

print("Missing values before cleaning:")
print(df.isnull().sum())

df["Age"] = df["Age"].fillna(df["Age"].mean())

print("\nMissing values after cleaning:")
print(df.isnull().sum())

print("\nCleaned DataFrame:")
print(df)

Missing values before cleaning:
Name     0
Marks    0
Age      1
dtype: int64

Missing values after cleaning:
Name     0
Marks    0
Age      0
dtype: int64

Cleaned DataFrame:
      Name  Marks   Age
0  Ranjita     85  20.0
1      Anu     78  21.0
2    Priya     92  21.0
3    Rahul     74  22.0

## Week 3 Client Project: Start the Dataset

In [46]:
data = {
    "Name": ["Ranjita", "Anu", "Priya", "Rahul", "Sneha", "Amit", "Kiran", "Neha"],
    "Branch": ["AIML", "CSE", "AIML", "CSE", "AIML", "CSE", "AIML", "CSE"],
    "Maths": [85, 78, 92, 74, None, 81, 88, 76],
    "Python": [90, 82, 95, 70, 86, None, 91, 79],
    "Attendance": [92, 85, 96, 78, 88, 91, None, 83]
}

df = pd.DataFrame(data)

print(df)

      Name Branch  Maths  Python  Attendance
0  Ranjita   AIML   85.0    90.0        92.0
1      Anu    CSE   78.0    82.0        85.0
2    Priya   AIML   92.0    95.0        96.0
3    Rahul    CSE   74.0    70.0        78.0
4    Sneha   AIML    NaN    86.0        88.0
5     Amit    CSE   81.0     NaN        91.0
6    Kiran   AIML   88.0    91.0         NaN
7     Neha    CSE   76.0    79.0        83.0

## Inspect the Client Dataset

In [47]:
print("First 5 rows:")
print(df.head())

print("\nDataset shape:")
print(df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

First 5 rows:
      Name Branch  Maths  Python  Attendance
0  Ranjita   AIML   85.0    90.0        92.0
1      Anu    CSE   78.0    82.0        85.0
2    Priya   AIML   92.0    95.0        96.0
3    Rahul    CSE   74.0    70.0        78.0
4    Sneha   AIML    NaN    86.0        88.0

Dataset shape:
(8, 5)

Column names:
['Name', 'Branch', 'Maths', 'Python', 'Attendance']

Data types:
Name           object
Branch         object
Maths         float64
Python        float64
Attendance    float64
dtype: object

## Find Missing Values

In [48]:
print(df.isnull().sum())

Name          0
Branch        0
Maths         1
Python        1
Attendance    1
dtype: int64

## Finding Missing Values

In [49]:
df["Maths"] = df["Maths"].fillna(df["Maths"].mean())
df["Python"] = df["Python"].fillna(df["Python"].mean())
df["Attendance"] = df["Attendance"].fillna(df["Attendance"].mean())

print(df)

      Name Branch  Maths     Python  Attendance
0  Ranjita   AIML   85.0  90.000000   92.000000
1      Anu    CSE   78.0  82.000000   85.000000
2    Priya   AIML   92.0  95.000000   96.000000
3    Rahul    CSE   74.0  70.000000   78.000000
4    Sneha   AIML   82.0  86.000000   88.000000
5     Amit    CSE   81.0  84.714286   91.000000
6    Kiran   AIML   88.0  91.000000   87.571429
7     Neha    CSE   76.0  79.000000   83.000000

In [50]:
print("\nMissing values after cleaning:")
print(df.isnull().sum())

Missing values after cleaning:
Name          0
Branch        0
Maths         0
Python        0
Attendance    0
dtype: int64

## Check for Duplicate Rows

In [51]:
print("Number of duplicate rows:", df.duplicated().sum())

Number of duplicate rows: 0

In [52]:
cleaned_df = df.drop_duplicates()

print("Rows before removing duplicates:", len(df))
print("Rows after removing duplicates:", len(cleaned_df))

Rows before removing duplicates: 8
Rows after removing duplicates: 8

## Calculate Average Marks

In [53]:
print("Average Maths marks:", df["Maths"].mean())
print("Average Python marks:", df["Python"].mean())
print("Average Attendance:", df["Attendance"].mean())

Average Maths marks: 82.0
Average Python marks: 84.71428571428572
Average Attendance: 87.57142857142857

## Calculate Average by Branch

In [54]:
branch_average = df.groupby("Branch")[["Maths", "Python", "Attendance"]].mean()

print(branch_average)

        Maths     Python  Attendance
Branch
AIML    86.75  90.500000   90.892857
CSE     77.25  78.928571   84.250000

## Find the Highest-Performing Branch

In [55]:
df["Overall_Average"] = df[["Maths", "Python"]].mean(axis=1)

branch_performance = df.groupby("Branch")["Overall_Average"].mean()

print(branch_performance)

Branch
AIML    88.625000
CSE     78.089286
Name: Overall_Average, dtype: float64

## Save the Cleaned Client Dataset

In [56]:
cleaned_df = df.drop_duplicates()

cleaned_df.to_csv("student_performance_cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

## Week 3 Summary

### Concepts Learned
- NumPy arrays and array operations
- NumPy broadcasting
- NumPy aggregation functions
- Pandas Series and DataFrames
- DataFrame indexing using `loc` and `iloc`
- Filtering and sorting data
- Grouping and aggregation using `groupby()`
- Handling missing values
- Removing duplicate rows
- Reading and writing CSV files
- Combining NumPy with Pandas

### Client Project
I created a student performance dataset and used Pandas and NumPy to:
- Inspect the dataset.
- Identify missing values.
- Fill missing values using column averages.
- Check and remove duplicate rows.
- Calculate subject-wise averages.
- Calculate branch-wise performance.
- Calculate overall student averages.
- Save the cleaned dataset as a CSV file.

### Output
The cleaned dataset was saved as:

`student_performance_cleaned.csv`